### ISSUE TITLE
Screen property not working

### ISSUE THREAD

**Issue by manijak** [NathanaelA/nativescript-platform#1]
I was trying to use the `screen` property to get proper with/height when using the `orientation` plugin. But the property does not work (both platforms). 

```
require( "nativescript-platform" );
console.log("screen info:", nsPlatform.screen);
console.log("screen width:", nsPlatform.screen.width);
```

Console result:
```
screen info: function () { return getResolution(); }
screen width:
```

**Comment by NathanaelA** [comment]
Thank you.  This is fixed in the current release along with some addition features.
